version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: todo_app_postgress_container
    environment:
      - POSTGRES_DB=todo_app_database
      - POSTGRES_USER=todo_svc_user
      - POSTGRES_PASSWORD=mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
