# Generated by Django 4.2.6 on 2023-12-12 02:29

from django.db import migrations

def bootstrap_todos(apps, schema_editor):
    Todo = apps.get_model('todo', 'Todo')
    
    initial_todos = [
        { 'title': 'First Todo', 'description': 'This is my first todo', 'completed': False },
        { 'title': 'Second Todo', 'description': 'This is my second todo', 'completed': False },
        { 'title': 'Third Todo', 'description': 'This is my third todo', 'completed': False } 
        ]

    for todo in initial_todos:
        Todo.objects.create(**todo)

class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(bootstrap_todos),
    ]
